# Generated by Django 5.1.5 on 2026-05-24 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dialer_cdr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=128, verbose_name='agent name')),
                ('status', models.IntegerField(choices=[(0, 'Logged Out'), (1, 'Available'), (2, 'On Break'), (3, 'On Demand')], default=0, verbose_name='status')),
                ('state', models.CharField(choices=[('Waiting', 'Waiting'), ('Receiving', 'Receiving'), ('In a queue call', 'In a Queue Call'), ('Idle', 'Idle')], default='Waiting', max_length=50, verbose_name='state')),
                ('contact', models.CharField(blank=True, help_text='SIP URI or phone number for agent', max_length=255, verbose_name='contact')),
                ('no_answer_delay_time', models.IntegerField(default=0, help_text='Seconds to wait for answer', verbose_name='no answer delay')),
                ('max_no_answer', models.IntegerField(default=3, help_text='Max missed calls before logout', verbose_name='max no answer')),
                ('wrap_up_time', models.IntegerField(default=0, help_text='Seconds after call before available', verbose_name='wrap up time')),
                ('reject_delay_time', models.IntegerField(default=0, help_text='Seconds delay after rejection', verbose_name='reject delay')),
                ('busy_delay_time', models.IntegerField(default=0, help_text='Seconds delay when busy', verbose_name='busy delay')),
                ('last_bridge_start', models.DateTimeField(blank=True, null=True, verbose_name='last call start')),
                ('last_bridge_end', models.DateTimeField(blank=True, null=True, verbose_name='last call end')),
                ('talk_time', models.IntegerField(default=0, help_text='Total seconds on calls', verbose_name='total talk time')),
                ('calls_answered', models.IntegerField(default=0, verbose_name='calls answered')),
                ('last_status_change', models.DateTimeField(auto_now=True, verbose_name='last status change')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'agent',
                'verbose_name_plural': 'agents',
                'db_table': 'callcenter_agent',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=128, verbose_name='queue name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('strategy', models.IntegerField(choices=[(1, 'Ring All'), (2, 'Longest Idle Agent'), (3, 'Round Robin'), (4, 'Top Down'), (5, 'Agent with Least Talk Time'), (6, 'Agent with Fewest Calls'), (7, 'Sequentially by Agent Order'), (8, 'Random')], default=2, verbose_name='routing strategy')),
                ('moh_sound', models.CharField(blank=True, help_text='Audio file path for hold music', max_length=255, verbose_name='music on hold')),
                ('time_base_score', models.IntegerField(default=0, help_text='Seconds before increasing priority', verbose_name='time base score')),
                ('tier_rules_apply', models.BooleanField(default=False, help_text='Route calls based on tier levels', verbose_name='apply tier rules')),
                ('tier_rule_wait_second', models.IntegerField(default=0, help_text='Seconds to wait before trying next tier', verbose_name='tier wait seconds')),
                ('tier_rule_wait_multiply_level', models.BooleanField(default=False, help_text='Multiply wait time by tier level', verbose_name='multiply tier wait')),
                ('tier_rule_no_agent_no_wait', models.BooleanField(default=False, help_text='Skip to next tier immediately if no agents', verbose_name='no wait if no agents')),
                ('max_wait_time', models.IntegerField(default=0, help_text='Maximum seconds caller will wait (0 = unlimited)', verbose_name='max wait time')),
                ('max_wait_time_with_no_agent', models.IntegerField(default=0, help_text='Max wait if no agents available', verbose_name='max wait without agent')),
                ('discard_abandoned_after', models.IntegerField(default=60, help_text='Seconds before removing abandoned calls', verbose_name='discard abandoned after')),
                ('ring_progressively_delay', models.IntegerField(default=10, help_text='Seconds between ring attempts', verbose_name='ring delay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'queue',
                'verbose_name_plural': 'queues',
                'db_table': 'callcenter_queue',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QueueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('session_uuid', models.CharField(help_text='FreeSWITCH session UUID', max_length=255, verbose_name='session UUID')),
                ('caller_number', models.CharField(max_length=80, verbose_name='caller number')),
                ('caller_name', models.CharField(blank=True, max_length=128, verbose_name='caller name')),
                ('joined_epoch', models.BigIntegerField(help_text='Unix timestamp when joined queue', verbose_name='joined time')),
                ('serving_system', models.CharField(blank=True, help_text='FreeSWITCH node handling call', max_length=255, verbose_name='serving system')),
                ('state', models.CharField(default='Waiting', max_length=50, verbose_name='state')),
                ('abandoned_epoch', models.BigIntegerField(blank=True, null=True, verbose_name='abandoned time')),
                ('callrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_memberships', to='dialer_cdr.callrequest', verbose_name='call request')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='callcenter.queue', verbose_name='queue')),
                ('serving_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serving_calls', to='callcenter.agent', verbose_name='serving agent')),
            ],
            options={
                'verbose_name': 'queue member',
                'verbose_name_plural': 'queue members',
                'db_table': 'callcenter_queue_member',
                'ordering': ['joined_epoch'],
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('level', models.IntegerField(choices=[(1, 'Level 1 (Highest)'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5 (Lowest)')], default=1, verbose_name='tier level')),
                ('position', models.IntegerField(choices=[(1, 'Position 1'), (2, 'Position 2'), (3, 'Position 3'), (4, 'Position 4'), (5, 'Position 5'), (6, 'Position 6'), (7, 'Position 7'), (8, 'Position 8'), (9, 'Position 9'), (10, 'Position 10')], default=1, verbose_name='position')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='callcenter.agent', verbose_name='agent')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='callcenter.queue', verbose_name='queue')),
            ],
            options={
                'verbose_name': 'tier',
                'verbose_name_plural': 'tiers',
                'db_table': 'callcenter_tier',
                'ordering': ['queue', 'level', 'position'],
                'unique_together': {('queue', 'agent')},
            },
        ),
    ]
