# Generated by Django 5.1.5 on 2026-05-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callcenter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="sip_extension",
            field=models.CharField(
                blank=True,
                help_text="Extension number the agent registers with (e.g. 1001)",
                max_length=20,
                verbose_name="SIP extension",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="sip_password",
            field=models.CharField(
                blank=True,
                help_text="Password the agent uses to register their SIP phone",
                max_length=128,
                verbose_name="SIP password",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="contact",
            field=models.CharField(
                blank=True,
                help_text="SIP URI or phone number for agent (e.g. user/1001)",
                max_length=255,
                verbose_name="contact",
            ),
        ),
    ]
