# Generated by Django 5.1.5 on 2026-05-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callcenter", "0002_agent_sip_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="last_heartbeat",
            field=models.DateTimeField(
                blank=True,
                help_text="Last WebSocket heartbeat — used to detect dropped connections",
                null=True,
                verbose_name="last heartbeat",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="ws_connected",
            field=models.BooleanField(
                default=False,
                help_text="True while the agent desktop WebSocket is connected",
                verbose_name="websocket connected",
            ),
        ),
    ]
