# Generated by Django 5.1.5 on 2026-05-24 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='Settings name', max_length=50, verbose_name='name')),
                ('max_frequency', models.PositiveIntegerField(default=100, help_text='Maximum calls per minute', verbose_name='max frequency')),
                ('callmaxduration', models.PositiveIntegerField(default=1800, help_text='Maximum call duration in seconds (1800 = 30 minutes)', verbose_name='max call duration')),
                ('maxretry', models.PositiveIntegerField(default=3, help_text='Maximum retries per contact', verbose_name='max retries')),
                ('max_calltimeout', models.PositiveIntegerField(default=45, help_text='Maximum call timeout in seconds', verbose_name='timeout on call')),
                ('max_cpg', models.PositiveIntegerField(default=100, help_text='Maximum number of campaigns per tenant', verbose_name='maximum number of campaigns')),
                ('max_subr_cpg', models.PositiveIntegerField(default=100000, help_text='Maximum subscribers per campaign. Unlimited if 0', verbose_name='maximum subscribers per campaign')),
                ('max_contact', models.PositiveIntegerField(default=1000000, help_text='Maximum number of contacts per tenant. Unlimited if 0', verbose_name='maximum number of contacts')),
                ('blacklist', models.TextField(blank=True, default='', help_text="Use regular expressions to blacklist phone numbers. Example: '^[2-4][1]+' blocks numbers starting with 2,3,4 followed by 1", verbose_name='blacklist')),
                ('whitelist', models.TextField(blank=True, default='', help_text='Use regular expressions to whitelist phone numbers', verbose_name='whitelist')),
                ('sms_max_frequency', models.PositiveIntegerField(default=100, help_text='Maximum SMS per minute', verbose_name='max SMS frequency')),
                ('sms_maxretry', models.PositiveIntegerField(default=3, help_text='Maximum SMS retries per contact', verbose_name='max SMS retries')),
                ('sms_max_number_campaign', models.PositiveIntegerField(default=10, help_text='Maximum number of SMS campaigns', verbose_name='max SMS campaigns')),
                ('sms_max_number_subscriber_campaign', models.PositiveIntegerField(default=10000, help_text='Maximum subscribers per SMS campaign', verbose_name='max subscribers of SMS campaigns')),
                ('tenant', models.OneToOneField(help_text='Tenant these settings apply to', on_delete=django.db.models.deletion.CASCADE, related_name='dialer_setting', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'dialer setting',
                'verbose_name_plural': 'dialer settings',
                'db_table': 'dialer_setting',
                'ordering': ['name'],
            },
        ),
    ]
