# Generated by Django 5.1.5 on 2026-05-24 09:40

import apps.dialer_campaign.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiofield', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dialer_contact', '0001_initial'),
        ('dialer_gateway', '0001_initial'),
        ('dnc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('campaign_code', models.CharField(default=apps.dialer_campaign.models.generate_campaign_code, editable=False, max_length=20, unique=True, verbose_name='campaign code')),
                ('name', models.CharField(max_length=100, verbose_name='campaign name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.IntegerField(choices=[(1, 'Pause'), (2, 'Abort'), (3, 'Start'), (4, 'End'), (5, 'Pending')], default=5, verbose_name='status')),
                ('callerid', models.CharField(blank=True, max_length=80, verbose_name='caller ID')),
                ('caller_name', models.CharField(blank=True, max_length=80, verbose_name='caller name')),
                ('startingdate', models.DateTimeField(verbose_name='starting date')),
                ('expirationdate', models.DateTimeField(verbose_name='expiration date')),
                ('daily_start_time', models.TimeField(default='00:00:00', verbose_name='daily start time')),
                ('daily_stop_time', models.TimeField(default='23:59:59', verbose_name='daily stop time')),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('frequency', models.PositiveIntegerField(default=10, help_text='Calls per minute', verbose_name='frequency')),
                ('calltimeout', models.PositiveIntegerField(default=30, help_text='Seconds to wait for answer', verbose_name='call timeout')),
                ('callmaxduration', models.PositiveIntegerField(default=1800, help_text='Maximum call duration in seconds', verbose_name='max call duration')),
                ('maxretry', models.PositiveIntegerField(default=0, help_text='Maximum retries per contact', verbose_name='max retries')),
                ('intervalretry', models.PositiveIntegerField(default=300, help_text='Seconds between retries', verbose_name='interval retry')),
                ('completion_maxretry', models.PositiveIntegerField(default=0, help_text='Retries for incomplete calls', verbose_name='completion max retries')),
                ('completion_intervalretry', models.PositiveIntegerField(default=900, help_text='Seconds between completion retries', verbose_name='completion interval retry')),
                ('check_dnc', models.BooleanField(default=False, help_text='Check DNC list before calling', verbose_name='check DNC')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('voicemail', models.BooleanField(default=False, verbose_name='detect voicemail')),
                ('amd_behavior', models.IntegerField(choices=[(0, 'Disable'), (1, 'Always Play Message'), (2, 'Play Only to Human'), (3, 'Play Only to Machine')], default=0, verbose_name='AMD behavior')),
                ('extra_data', models.CharField(blank=True, max_length=120, verbose_name='extra data')),
                ('external_link', models.JSONField(blank=True, null=True, verbose_name='external link')),
                ('has_been_started', models.BooleanField(default=False, verbose_name='has been started')),
                ('has_been_duplicated', models.BooleanField(default=False, verbose_name='has been duplicated')),
                ('imported_phonebook', models.CharField(blank=True, max_length=500, verbose_name='imported phonebook')),
                ('totalcontact', models.PositiveIntegerField(default=0, verbose_name='total contacts')),
                ('completed', models.PositiveIntegerField(default=0, verbose_name='completed')),
                ('aleg_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='dialer_gateway.gateway', verbose_name='A-leg gateway')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('dnc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dnc.dnc', verbose_name='DNC list')),
                ('dnc_list', models.ForeignKey(blank=True, help_text='Numbers in this DNC list will be skipped', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='dnc.dnc', verbose_name='DNC list')),
                ('phonebook', models.ManyToManyField(blank=True, related_name='campaigns', to='dialer_contact.phonebook', verbose_name='phonebooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('voicemail_audiofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voicemail_campaigns', to='audiofield.audiofile', verbose_name='voicemail audio file')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'db_table': 'dialer_campaign',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('duplicate_contact', models.CharField(help_text='Cached phone number from contact', max_length=90, verbose_name='duplicate contact')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Pause'), (3, 'Abort'), (4, 'Fail'), (5, 'Sent'), (6, 'In Process'), (7, 'Not Authorized'), (8, 'Completed')], default=1, verbose_name='status')),
                ('count_attempt', models.PositiveIntegerField(default=0, verbose_name='attempt count')),
                ('last_attempt', models.DateTimeField(blank=True, null=True, verbose_name='last attempt')),
                ('completion_count_attempt', models.PositiveIntegerField(default=0, verbose_name='completion attempt count')),
                ('last_completion_attempt', models.DateTimeField(blank=True, null=True, verbose_name='last completion attempt')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='dialer_campaign.campaign', verbose_name='campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='dialer_contact.contact', verbose_name='contact')),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
                'db_table': 'dialer_subscriber',
                'ordering': ['created_date'],
                'unique_together': {('campaign', 'contact')},
            },
        ),
    ]
