# Generated by Django 5.1.5 on 2026-05-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dialer_campaign", "0002_campaign_dial_mode_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="lines_per_agent",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Simultaneous calls to dial per available agent (1 = progressive, 2-3 = predictive)",
                verbose_name="lines per agent",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="frequency",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum calls per minute (upper cap)",
                verbose_name="frequency",
            ),
        ),
    ]
