# Generated by Django 5.1.5 on 2026-06-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agent", "0003_alter_aiagent_tts_speaker"),
        ("dialer_campaign", "0003_campaign_lines_per_agent_alter_campaign_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="ai_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, answered calls are handled by this AI agent instead of a human",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="ai_agent.aiagent",
                verbose_name="AI agent",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="ai_max_concurrent",
            field=models.PositiveIntegerField(
                default=5,
                help_text="How many AI calls can run at once for this campaign",
                verbose_name="max concurrent AI calls",
            ),
        ),
    ]
