# Generated by Django 5.1.5 on 2026-06-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dialer_campaign", "0004_campaign_ai_agent_campaign_ai_max_concurrent"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="allow_duplicate_contacts",
            field=models.BooleanField(
                default=False,
                help_text="Import every contact row even if the phone number repeats (default: dedupe to one call per number)",
                verbose_name="allow duplicate numbers",
            ),
        ),
    ]
