# Generated by Django 5.1.5 on 2026-05-24 09:40

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=128, verbose_name='DNC list name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dnc_lists', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'DNC list',
                'verbose_name_plural': 'DNC lists',
                'db_table': 'dnc',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DNCContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number to exclude from calling', max_length=128, region=None, verbose_name='phone number')),
                ('dnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='dnc.dnc', verbose_name='DNC list')),
            ],
            options={
                'verbose_name': 'DNC contact',
                'verbose_name_plural': 'DNC contacts',
                'db_table': 'dnc_contact',
                'indexes': [models.Index(fields=['phone_number'], name='dnc_contact_phone_n_660574_idx')],
                'unique_together': {('dnc', 'phone_number')},
            },
        ),
    ]
