"""Initial migration for the AI Agent app."""
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        ("callcenter", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAgent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_date", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=120, verbose_name="agent name")),
                ("description", models.TextField(blank=True)),
                ("status", models.IntegerField(choices=[(0, "Draft"), (1, "Active"), (2, "Paused"), (3, "Training")], default=0)),
                ("persona_name", models.CharField(default="Assistant", max_length=80)),
                ("greeting", models.TextField(default="Hello! How can I help you today?")),
                ("system_prompt", models.TextField(blank=True)),
                ("temperature", models.FloatField(default=0.6)),
                ("max_response_tokens", models.PositiveIntegerField(default=300)),
                ("llm_provider", models.CharField(choices=[("sarvam", "Sarvam (Indic-native)"), ("gemini", "Google Gemini")], default="sarvam", max_length=20)),
                ("sarvam_llm_model", models.CharField(blank=True, choices=[("sarvam-105b", "Sarvam 105B (flagship)"), ("sarvam-30b", "Sarvam 30B (balanced)"), ("sarvam-m", "Sarvam-M 24B (legacy)")], default="sarvam-30b", max_length=30)),
                ("gemini_model", models.CharField(blank=True, choices=[("gemini-2.0-flash", "Gemini 2.0 Flash"), ("gemini-1.5-pro", "Gemini 1.5 Pro"), ("gemini-1.5-flash", "Gemini 1.5 Flash")], default="gemini-2.0-flash", max_length=40)),
                ("enable_thinking", models.BooleanField(default=False)),
                ("primary_language", models.CharField(choices=[("unknown", "Auto-detect"), ("en-IN", "English (India)"), ("hi-IN", "Hindi"), ("bn-IN", "Bengali"), ("ta-IN", "Tamil"), ("te-IN", "Telugu"), ("gu-IN", "Gujarati"), ("kn-IN", "Kannada"), ("ml-IN", "Malayalam"), ("mr-IN", "Marathi"), ("pa-IN", "Punjabi"), ("od-IN", "Odia")], default="hi-IN", max_length=10)),
                ("auto_detect_language", models.BooleanField(default=True)),
                ("stt_model", models.CharField(choices=[("saaras:v3", "Saaras v3 (recommended)"), ("saarika:v2.5", "Saarika v2.5 (legacy)")], default="saaras:v3", max_length=20)),
                ("stt_mode", models.CharField(choices=[("transcribe", "Transcribe (same language)"), ("translate", "Translate to English"), ("codemix", "Code-mixed (Hinglish etc.)")], default="transcribe", max_length=15)),
                ("tts_model", models.CharField(choices=[("bulbul:v3", "Bulbul v3 (recommended)"), ("bulbul:v2", "Bulbul v2 (legacy)")], default="bulbul:v3", max_length=15)),
                ("tts_speaker", models.CharField(default="anand", max_length=30)),
                ("tts_pace", models.FloatField(default=1.0)),
                ("tts_temperature", models.FloatField(default=0.6)),
                ("allow_human_transfer", models.BooleanField(default=True)),
                ("allow_callback", models.BooleanField(default=True)),
                ("confidence_transfer_threshold", models.FloatField(default=0.4)),
                ("max_call_duration_seconds", models.PositiveIntegerField(default=600)),
                ("kb_last_indexed", models.DateTimeField(blank=True, null=True)),
                ("kb_chunk_count", models.PositiveIntegerField(default=0)),
                ("transfer_queue", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_transfer_agents", to="callcenter.queue")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_agents", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "AI agent", "db_table": "ai_agent", "ordering": ["-created_date"]},
        ),
        migrations.CreateModel(
            name="AISubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_date", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(default=False, verbose_name="active")),
                ("plan_name", models.CharField(default="standard", max_length=80)),
                ("max_agents", models.PositiveIntegerField(default=1)),
                ("monthly_minute_quota", models.PositiveIntegerField(default=1000)),
                ("minutes_used_this_period", models.PositiveIntegerField(default=0)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("tenant", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="ai_subscription", to="tenants.tenant")),
            ],
            options={"verbose_name": "AI subscription", "db_table": "ai_subscription"},
        ),
        migrations.CreateModel(
            name="AIKnowledgeItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_date", models.DateTimeField(auto_now=True, db_index=True)),
                ("source_type", models.CharField(choices=[("product", "Product detail"), ("faq", "FAQ"), ("document", "Uploaded document"), ("freeform", "Free-form note")], default="product", max_length=15)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("product_name", models.CharField(blank=True, max_length=200)),
                ("product_price", models.CharField(blank=True, max_length=80)),
                ("product_attributes", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="knowledge_items", to="ai_agent.aiagent")),
            ],
            options={"verbose_name": "AI knowledge item", "db_table": "ai_knowledge_item", "ordering": ["-created_date"]},
        ),
        migrations.CreateModel(
            name="AICallSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_date", models.DateTimeField(auto_now=True, db_index=True)),
                ("call_uuid", models.CharField(blank=True, db_index=True, max_length=120)),
                ("livekit_room", models.CharField(blank=True, max_length=160)),
                ("caller_number", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("outcome", models.CharField(blank=True, choices=[("resolved", "Resolved by AI"), ("transferred", "Transferred to human"), ("callback", "Callback scheduled"), ("abandoned", "Caller hung up"), ("failed", "Failed / error")], max_length=15)),
                ("detected_language", models.CharField(blank=True, max_length=10)),
                ("transfer_reason", models.CharField(blank=True, choices=[("customer_request", "Customer asked for human"), ("low_confidence", "AI unsure"), ("escalation", "Policy escalation"), ("sentiment", "Negative sentiment")], max_length=20)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="call_sessions", to="ai_agent.aiagent")),
                ("transferred_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_handoffs", to="callcenter.agent")),
            ],
            options={"verbose_name": "AI call session", "db_table": "ai_call_session", "ordering": ["-created_date"]},
        ),
        migrations.CreateModel(
            name="AIKnowledgeChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_date", models.DateTimeField(auto_now=True, db_index=True)),
                ("text", models.TextField()),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="knowledge_chunks", to="ai_agent.aiagent")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="ai_agent.aiknowledgeitem")),
            ],
            options={"db_table": "ai_knowledge_chunk"},
        ),
        migrations.CreateModel(
            name="AICallback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_date", models.DateTimeField(auto_now=True, db_index=True)),
                ("caller_number", models.CharField(max_length=64)),
                ("requested_for", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("done", "Completed"), ("cancelled", "Cancelled")], default="pending", max_length=12)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="callbacks", to="ai_agent.aiagent")),
                ("assigned_agent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_callbacks", to="callcenter.agent")),
                ("session", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="callbacks", to="ai_agent.aicallsession")),
            ],
            options={"verbose_name": "AI callback", "db_table": "ai_callback", "ordering": ["requested_for"]},
        ),
        migrations.CreateModel(
            name="AITranscriptTurn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_date", models.DateTimeField(auto_now=True, db_index=True)),
                ("role", models.CharField(choices=[("caller", "Caller"), ("ai", "AI"), ("system", "System")], max_length=10)),
                ("text", models.TextField()),
                ("language", models.CharField(blank=True, max_length=10)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="turns", to="ai_agent.aicallsession")),
            ],
            options={"db_table": "ai_transcript_turn", "ordering": ["started_at", "id"]},
        ),
        migrations.AddIndex(
            model_name="aiknowledgechunk",
            index=models.Index(fields=["agent"], name="ai_knowledg_agent_i_idx"),
        ),
        migrations.AddIndex(
            model_name="aicallsession",
            index=models.Index(fields=["agent", "outcome"], name="ai_call_ses_agent_i_idx"),
        ),
    ]
