# Generated by Django 5.1.5 on 2026-06-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agent", "0001_initial"),
        ("callcenter", "0003_agent_last_heartbeat_agent_ws_connected"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aicallsession",
            new_name="ai_call_ses_agent_i_8e518e_idx",
            old_name="ai_call_ses_agent_i_idx",
        ),
        migrations.RenameIndex(
            model_name="aiknowledgechunk",
            new_name="ai_knowledg_agent_i_a17513_idx",
            old_name="ai_knowledg_agent_i_idx",
        ),
        migrations.AlterField(
            model_name="aiagent",
            name="allow_callback",
            field=models.BooleanField(
                default=True,
                help_text="If no human available, offer to schedule a callback",
            ),
        ),
        migrations.AlterField(
            model_name="aiagent",
            name="confidence_transfer_threshold",
            field=models.FloatField(
                default=0.4,
                help_text="Transfer to human if AI confidence drops below this (0-1)",
            ),
        ),
        migrations.AlterField(
            model_name="aiagent",
            name="enable_thinking",
            field=models.BooleanField(
                default=False,
                help_text="Sarvam hybrid 'think' mode / Gemini reasoning for hard queries",
            ),
        ),
        migrations.AlterField(
            model_name="aiagent",
            name="greeting",
            field=models.TextField(
                default="Hello! How can I help you today?",
                help_text="First thing the AI says when it answers",
            ),
        ),
        migrations.AlterField(
            model_name="aiagent",
            name="persona_name",
            field=models.CharField(
                default="Assistant",
                help_text="Name the AI uses to introduce itself",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="aiagent",
            name="system_prompt",
            field=models.TextField(
                blank=True,
                help_text="Base instructions. Knowledge base is appended automatically.",
            ),
        ),
        migrations.AlterField(
            model_name="aiagent",
            name="transfer_queue",
            field=models.ForeignKey(
                blank=True,
                help_text="Human queue to transfer to when escalating",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_transfer_agents",
                to="callcenter.queue",
            ),
        ),
        migrations.AlterField(
            model_name="aiagent",
            name="tts_pace",
            field=models.FloatField(default=1.0, help_text="0.5-2.0 for v3"),
        ),
        migrations.AlterField(
            model_name="aiagent",
            name="tts_speaker",
            field=models.CharField(
                default="anand",
                help_text="Bulbul speaker id (lowercase, must match model)",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="aiagent",
            name="tts_temperature",
            field=models.FloatField(default=0.6, help_text="v3 only, 0.01-2.0"),
        ),
        migrations.AlterField(
            model_name="aicallback",
            name="requested_for",
            field=models.DateTimeField(
                help_text="When the customer wants to be called back"
            ),
        ),
        migrations.AlterField(
            model_name="aiknowledgeitem",
            name="content",
            field=models.TextField(help_text="The knowledge text the AI can draw on"),
        ),
        migrations.AlterField(
            model_name="aisubscription",
            name="monthly_minute_quota",
            field=models.PositiveIntegerField(
                default=1000, help_text="AI talk-minutes per month"
            ),
        ),
        migrations.AlterField(
            model_name="aisubscription",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_subscription",
                to="tenants.tenant",
                verbose_name="tenant",
            ),
        ),
    ]
