# Generated by Django 5.1.5 on 2026-06-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ai_agent",
            "0002_rename_ai_call_ses_agent_i_idx_ai_call_ses_agent_i_8e518e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiagent",
            name="tts_speaker",
            field=models.CharField(
                default="manan",
                help_text="Bulbul speaker id (lowercase, must match model)",
                max_length=30,
            ),
        ),
    ]
