# Generated by Django 5.1.5 on 2026-06-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agent", "0003_alter_aiagent_tts_speaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiagent",
            name="call_direction",
            field=models.CharField(
                choices=[
                    ("inbound", "Inbound — answers customer calls"),
                    ("outbound", "Outbound — sales executive who calls customers"),
                ],
                default="inbound",
                help_text="Outbound agents lead the conversation and pitch; inbound agents assist callers",
                max_length=10,
            ),
        ),
    ]
