# Generated by Django 5.1.5 on 2026-05-24 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiofield', '0001_initial'),
        ('dialer_cdr', '0001_initial'),
        ('mod_sms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=90, verbose_name='survey name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Sealed'), (3, 'Archived')], default=1, help_text='Draft surveys can be edited, Sealed surveys are locked', verbose_name='status')),
                ('campaign_count', models.PositiveIntegerField(default=0, help_text='Number of campaigns using this survey', verbose_name='campaign count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'survey',
                'verbose_name_plural': 'surveys',
                'db_table': 'survey',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('response_data', models.JSONField(default=dict, help_text='JSON object containing all section responses', verbose_name='response data')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('callrequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='dialer_cdr.callrequest', verbose_name='call request')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.survey', verbose_name='survey')),
            ],
            options={
                'verbose_name': 'survey response',
                'verbose_name_plural': 'survey responses',
                'db_table': 'survey_response',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SurveySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('section_type', models.IntegerField(choices=[(1, 'Play Message'), (2, 'Multi-Choice'), (3, 'Rating Question'), (4, 'Capture Digits'), (5, 'Record Message'), (6, 'Call Transfer'), (7, 'Hangup'), (8, 'Conference'), (9, 'DNC (Do Not Call)'), (10, 'Send SMS')], verbose_name='section type')),
                ('name', models.CharField(max_length=90, verbose_name='section name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('key_0', models.CharField(blank=True, max_length=150, verbose_name='key 0')),
                ('key_1', models.CharField(blank=True, max_length=150, verbose_name='key 1')),
                ('key_2', models.CharField(blank=True, max_length=150, verbose_name='key 2')),
                ('key_3', models.CharField(blank=True, max_length=150, verbose_name='key 3')),
                ('key_4', models.CharField(blank=True, max_length=150, verbose_name='key 4')),
                ('key_5', models.CharField(blank=True, max_length=150, verbose_name='key 5')),
                ('key_6', models.CharField(blank=True, max_length=150, verbose_name='key 6')),
                ('key_7', models.CharField(blank=True, max_length=150, verbose_name='key 7')),
                ('key_8', models.CharField(blank=True, max_length=150, verbose_name='key 8')),
                ('key_9', models.CharField(blank=True, max_length=150, verbose_name='key 9')),
                ('rating_laps', models.PositiveIntegerField(default=0, help_text='Minimum rating value', verbose_name='rating low')),
                ('rating_high', models.PositiveIntegerField(default=0, help_text='Maximum rating value', verbose_name='rating high')),
                ('number_digits', models.PositiveIntegerField(default=1, help_text='Expected number of digits to capture', verbose_name='number of digits')),
                ('min_number_digits', models.PositiveIntegerField(default=1, verbose_name='min number of digits')),
                ('max_number_digits', models.PositiveIntegerField(default=10, verbose_name='max number of digits')),
                ('timeout', models.PositiveIntegerField(default=5, help_text='Seconds to wait for input', verbose_name='timeout')),
                ('max_record_time', models.PositiveIntegerField(default=30, help_text='Maximum recording duration in seconds', verbose_name='max record time')),
                ('phonenumber', models.CharField(blank=True, help_text='Number to transfer call to', max_length=80, verbose_name='phone number')),
                ('dial_timeout', models.PositiveIntegerField(default=30, help_text='Seconds to wait for transfer answer', verbose_name='dial timeout')),
                ('conference_number', models.CharField(blank=True, max_length=80, verbose_name='conference number')),
                ('sms_text', models.TextField(blank=True, help_text='SMS message to send', verbose_name='SMS text')),
                ('retries', models.PositiveIntegerField(default=0, help_text='Number of retry attempts for invalid input', verbose_name='retries')),
                ('validate_number', models.BooleanField(default=False, verbose_name='validate as number')),
                ('audiofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_sections', to='audiofield.audiofile', verbose_name='audio file')),
                ('invalid_audiofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invalid_for_sections', to='audiofield.audiofile', verbose_name='invalid input audio')),
                ('sms_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_sections', to='mod_sms.smsgateway', verbose_name='SMS gateway')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='survey.survey', verbose_name='survey')),
            ],
            options={
                'verbose_name': 'survey section',
                'verbose_name_plural': 'survey sections',
                'db_table': 'survey_section',
                'ordering': ['survey', 'order'],
                'unique_together': {('survey', 'order')},
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='entry_section',
            field=models.ForeignKey(blank=True, help_text='First section to play when survey starts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_for_surveys', to='survey.surveysection', verbose_name='entry section'),
        ),
        migrations.CreateModel(
            name='SurveyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('key_value', models.CharField(help_text='DTMF key or condition value (0-9, *, #, any, timeout)', max_length=10, verbose_name='key value')),
                ('goto_section', models.ForeignKey(help_text='Section to jump to when condition matches', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_branches', to='survey.surveysection', verbose_name='goto section')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='survey.surveysection', verbose_name='from section')),
            ],
            options={
                'verbose_name': 'survey branch',
                'verbose_name_plural': 'survey branches',
                'db_table': 'survey_branch',
                'unique_together': {('section', 'key_value')},
            },
        ),
    ]
