# Generated by Django 5.1.5 on 2026-05-24 09:40

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='Phonebook name', max_length=90, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Phonebook notes', null=True, verbose_name='description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonebooks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'phonebook',
                'verbose_name_plural': 'phonebooks',
                'db_table': 'dialer_phonebook',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number in E.164 format (e.g., +14155552671)', max_length=128, region=None, verbose_name='contact number')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1, verbose_name='status')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='last name')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='first name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('unit_number', models.CharField(blank=True, max_length=50, verbose_name='unit number')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='state/province')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='country')),
                ('description', models.TextField(blank=True, help_text='Notes about this contact', verbose_name='description')),
                ('additional_vars', models.JSONField(blank=True, help_text='Additional contact data in JSON format', null=True, verbose_name='additional variables')),
                ('phonebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='dialer_contact.phonebook', verbose_name='phonebook')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'dialer_contact',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['contact', 'status'], name='dialer_cont_contact_e3a24f_idx'), models.Index(fields=['phonebook', 'status'], name='dialer_cont_phonebo_247bca_idx')],
            },
        ),
    ]
