# Generated by Django 5.1.5 on 2026-05-24 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('audio_file', models.FileField(help_text='Audio file (WAV, MP3, etc.)', upload_to='audio/%Y/%m/%d/', verbose_name='audio file')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds', verbose_name='duration')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes', verbose_name='file size')),
                ('format', models.CharField(blank=True, help_text='Audio format (wav, mp3, etc.)', max_length=10, verbose_name='format')),
                ('sample_rate', models.PositiveIntegerField(default=8000, help_text='Sample rate in Hz (8000 for telephony)', verbose_name='sample rate')),
                ('channels', models.PositiveIntegerField(default=1, help_text='Number of audio channels (1=mono, 2=stereo)', verbose_name='channels')),
                ('is_tts', models.BooleanField(default=False, help_text='Was this file generated via TTS?', verbose_name='TTS generated')),
                ('tts_text', models.TextField(blank=True, help_text='Text used to generate TTS audio', verbose_name='TTS text')),
                ('tts_language', models.CharField(blank=True, help_text='Language code for TTS (en-US, es-ES, etc.)', max_length=10, verbose_name='TTS language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audio file',
                'verbose_name_plural': 'audio files',
                'db_table': 'audiofile',
                'ordering': ['-created_date'],
            },
        ),
    ]
