# Generated by Django 5.1.5 on 2026-05-24 09:40

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dialer_contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=128, verbose_name='gateway name')),
                ('gateway_type', models.IntegerField(choices=[(1, 'Twilio'), (2, 'Plivo'), (3, 'Clickatell'), (4, 'Nexmo/Vonage'), (99, 'Custom HTTP')], default=1, verbose_name='gateway type')),
                ('account_sid', models.CharField(blank=True, help_text='Twilio Account SID or equivalent', max_length=255, verbose_name='account SID')),
                ('auth_token', models.CharField(blank=True, help_text='API authentication token', max_length=255, verbose_name='auth token')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API key')),
                ('base_url', models.URLField(blank=True, help_text='For custom HTTP gateways', verbose_name='base URL')),
                ('from_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Sender phone number', max_length=128, null=True, region=None, verbose_name='from number')),
                ('from_name', models.CharField(blank=True, help_text='Sender ID (alphanumeric)', max_length=15, verbose_name='from name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_gateways', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'SMS gateway',
                'verbose_name_plural': 'SMS gateways',
                'db_table': 'sms_gateway',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmsCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=128, verbose_name='campaign name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Pending'), (3, 'Started'), (4, 'Paused'), (5, 'Aborted'), (6, 'Ended')], default=1, verbose_name='status')),
                ('message_text', models.TextField(max_length=1600, verbose_name='message text')),
                ('startingdate', models.DateTimeField(verbose_name='start date')),
                ('expirationdate', models.DateTimeField(verbose_name='expiration date')),
                ('frequency', models.IntegerField(default=10, help_text='Messages per minute', verbose_name='frequency')),
                ('total_sent', models.PositiveIntegerField(default=0, verbose_name='total sent')),
                ('total_delivered', models.PositiveIntegerField(default=0, verbose_name='total delivered')),
                ('total_failed', models.PositiveIntegerField(default=0, verbose_name='total failed')),
                ('phonebook', models.ManyToManyField(help_text='Contact lists to send to', to='dialer_contact.phonebook', verbose_name='phonebooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='mod_sms.smsgateway', verbose_name='SMS gateway')),
            ],
            options={
                'verbose_name': 'SMS campaign',
                'verbose_name_plural': 'SMS campaigns',
                'db_table': 'sms_campaign',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('recipient', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='recipient')),
                ('sender', models.CharField(help_text='From number or sender ID', max_length=80, verbose_name='sender')),
                ('message', models.TextField(help_text='SMS message content (max 1600 chars)', max_length=1600, verbose_name='message text')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Sent'), (3, 'Delivered'), (4, 'Failed'), (5, 'Unsent')], default=1, verbose_name='status')),
                ('gateway_message_id', models.CharField(blank=True, help_text='External message ID from SMS provider', max_length=255, verbose_name='gateway message ID')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='sent date')),
                ('delivered_date', models.DateTimeField(blank=True, null=True, verbose_name='delivered date')),
                ('error', models.TextField(blank=True, verbose_name='error message')),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mod_sms.smsgateway', verbose_name='gateway')),
                ('sms_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mod_sms.smscampaign', verbose_name='SMS campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'SMS message',
                'verbose_name_plural': 'SMS messages',
                'db_table': 'sms_message',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['recipient'], name='sms_message_recipie_d24394_idx'), models.Index(fields=['status'], name='sms_message_status_8781f8_idx')],
            },
        ),
    ]
