# Generated by Django 5.1.5 on 2026-05-24 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='Gateway name', max_length=255, unique=True, verbose_name='name')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1, verbose_name='gateway status')),
                ('description', models.TextField(blank=True, help_text='Gateway provider notes', verbose_name='description')),
                ('addprefix', models.CharField(blank=True, max_length=60, verbose_name='add prefix')),
                ('removeprefix', models.CharField(blank=True, max_length=60, verbose_name='remove prefix')),
                ('gateways', models.CharField(help_text='Gateway string to dial (e.g., "sofia/gateway/myprovider/")', max_length=500, verbose_name='gateways')),
                ('gateway_codecs', models.CharField(blank=True, help_text='Codec string (e.g., "PCMA,PCMU")', max_length=500, verbose_name='gateway codecs')),
                ('gateway_timeouts', models.CharField(blank=True, help_text='Timeout in seconds (e.g., "10")', max_length=500, verbose_name='gateway timeouts')),
                ('gateway_retries', models.CharField(blank=True, help_text='Retry count per gateway (e.g., "2,1")', max_length=500, verbose_name='gateway retries')),
                ('originate_dial_string', models.CharField(blank=True, help_text='Channel variables for originate', max_length=500, verbose_name='originate dial string')),
                ('addparameter', models.CharField(blank=True, max_length=360, verbose_name='additional parameters')),
                ('secondused', models.IntegerField(blank=True, null=True, verbose_name='seconds used')),
                ('count_call', models.IntegerField(blank=True, null=True, verbose_name='call count')),
                ('count_in_use', models.IntegerField(blank=True, null=True, verbose_name='calls in use')),
                ('maximum_call', models.IntegerField(blank=True, help_text='Maximum concurrent calls', null=True, verbose_name='maximum calls')),
                ('failover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failover_gateways', to='dialer_gateway.gateway', verbose_name='failover gateway')),
            ],
            options={
                'verbose_name': 'gateway',
                'verbose_name_plural': 'gateways',
                'db_table': 'dialer_gateway',
                'ordering': ['name'],
            },
        ),
    ]
