# Generated by Django 5.1.5 on 2026-05-24 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dialer_campaign', '0001_initial'),
        ('dialer_gateway', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Callrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('request_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='request UUID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Failure'), (3, 'Retry'), (4, 'Success'), (5, 'Abort'), (6, 'Pause'), (7, 'In Process'), (8, 'Calling')], db_index=True, default=1, verbose_name='status')),
                ('call_type', models.IntegerField(choices=[(1, 'Allow Retry'), (2, 'Cannot Retry')], default=1, verbose_name='call type')),
                ('call_time', models.DateTimeField(db_index=True, help_text='When this call should be initiated', verbose_name='scheduled call time')),
                ('phone_number', models.CharField(db_index=True, max_length=80, verbose_name='phone number')),
                ('callerid', models.CharField(blank=True, max_length=80, verbose_name='caller ID')),
                ('timeout', models.PositiveIntegerField(default=30, help_text='Seconds to wait for answer', verbose_name='timeout')),
                ('timelimit', models.PositiveIntegerField(default=3600, help_text='Maximum call duration in seconds', verbose_name='time limit')),
                ('extra_dial_string', models.CharField(blank=True, help_text='Additional FreeSWITCH dial parameters', max_length=500, verbose_name='extra dial string')),
                ('num_attempt', models.PositiveIntegerField(default=0, verbose_name='number of attempts')),
                ('last_attempt_time', models.DateTimeField(blank=True, null=True, verbose_name='last attempt time')),
                ('result', models.CharField(blank=True, max_length=180, verbose_name='result')),
                ('hangup_cause', models.CharField(blank=True, max_length=80, verbose_name='hangup cause')),
                ('completed', models.BooleanField(db_index=True, default=False, verbose_name='completed')),
                ('extra_data', models.CharField(blank=True, max_length=120, verbose_name='extra data')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('alarm_request_id', models.PositiveIntegerField(default=0, verbose_name='alarm request ID')),
                ('aleg_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callrequests', to='dialer_gateway.gateway', verbose_name='A-leg gateway')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callrequests', to='dialer_campaign.campaign', verbose_name='campaign')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('parent_callrequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_callrequests', to='dialer_cdr.callrequest', verbose_name='parent callrequest')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callrequests', to='dialer_campaign.subscriber', verbose_name='subscriber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callrequests', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'call request',
                'verbose_name_plural': 'call requests',
                'db_table': 'dialer_callrequest',
                'ordering': ['call_time'],
            },
        ),
        migrations.CreateModel(
            name='VoIPCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('callid', models.CharField(db_index=True, help_text='FreeSWITCH UUID', max_length=120, verbose_name='call ID')),
                ('callerid', models.CharField(blank=True, max_length=120, verbose_name='caller ID')),
                ('phone_number', models.CharField(db_index=True, max_length=120, verbose_name='phone number')),
                ('starting_date', models.DateTimeField(db_index=True, verbose_name='start time')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Call duration in seconds', verbose_name='duration')),
                ('billsec', models.PositiveIntegerField(default=0, help_text='Billable seconds (after answer)', verbose_name='bill seconds')),
                ('disposition', models.CharField(blank=True, choices=[('ANSWER', 'Answer'), ('BUSY', 'Busy'), ('NOANSWER', 'No Answer'), ('CANCEL', 'Cancel'), ('CONGESTION', 'Congestion'), ('CHANUNAVAIL', 'Channel Unavailable'), ('DONTCALL', 'Do Not Call'), ('TORTURE', 'Torture'), ('INVALIDARGS', 'Invalid Arguments'), ('NORMAL_CLEARING', 'Normal Clearing'), ('ORIGINATOR_CANCEL', 'Originator Cancel'), ('NORMAL_TEMPORARY_FAILURE', 'Temporary Failure'), ('INVALID_GATEWAY', 'Invalid Gateway')], db_index=True, max_length=40, verbose_name='disposition')),
                ('hangup_cause', models.CharField(blank=True, max_length=40, verbose_name='hangup cause')),
                ('hangup_cause_q850', models.CharField(blank=True, max_length=10, verbose_name='Q.850 cause code')),
                ('amd_status', models.IntegerField(blank=True, choices=[(1, 'Person'), (2, 'Machine'), (3, 'Not Sure')], null=True, verbose_name='AMD status')),
                ('leg_type', models.IntegerField(choices=[(1, 'A-Leg'), (2, 'B-Leg')], default=1, verbose_name='leg type')),
                ('buy_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='buy rate')),
                ('buy_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='buy cost')),
                ('sell_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='sell rate')),
                ('sell_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='sell cost')),
                ('extradata', models.TextField(blank=True, help_text='Additional CDR data from FreeSWITCH', verbose_name='extra data')),
                ('callrequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voip_calls', to='dialer_cdr.callrequest', verbose_name='call request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voip_calls', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'VoIP call',
                'verbose_name_plural': 'VoIP calls',
                'db_table': 'dialer_cdr',
                'ordering': ['-starting_date'],
            },
        ),
        migrations.AddIndex(
            model_name='callrequest',
            index=models.Index(fields=['status', 'call_time'], name='dialer_call_status_b85ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='callrequest',
            index=models.Index(fields=['campaign', 'status'], name='dialer_call_campaig_944bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='voipcall',
            index=models.Index(fields=['disposition', 'starting_date'], name='dialer_cdr_disposi_0d800b_idx'),
        ),
        migrations.AddIndex(
            model_name='voipcall',
            index=models.Index(fields=['user', 'starting_date'], name='dialer_cdr_user_id_1b4ba1_idx'),
        ),
    ]
